name: Trigger Antora Site Build
on:
  push:
    branches-ignore: [ gh-pages ]
    tags: '**'
  repository_dispatch:
    types: request-build-reference # legacy
  #schedule:
  #- cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:
permissions:
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    # FIXME enable when pushed to spring-projects
    # if: github.repository_owner == 'spring-projects'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: sampledump/antora-build
          fetch-depth: 1
      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh workflow run "Antora Site" -R sampledump/antora-build -f build-refname=${{ github.ref_name }} -f module=commons
      - name: Dispatch (full build)
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh workflow run "Antora Site" -R sampledump/antora-build
